name: Build OpenWrt

on: 
  watch:
    types: [started]
    
env:
  repo_url: https://github.com/lede-project/source
  repo_branch: reboot
  repo_os: openwrt
  config: .config22
  diy_sh: diy.sh
  model: PSG1218
  TZ: Asia/Shanghai
  newpack: true66
  ssh: true66
  set: true


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: 清理环境
      run: |
        wget https://drive.google.com/uc?export=download&confirm=c0UI&id=1M2BkRuR94NRSl6OhNjHqA0BFp2BtGFNb Fluid-1.4-Rum-UNOFFICIAL-m1882-20210503.zip
        ls
