name: Build OpenWrt

on: 
  watch:
    types: [started]
    
env:
  repo_url: https://github.com/lede-project/source
  repo_branch: reboot
  repo_os: openwrt
  config: .config22
  diy_sh: diy.sh
  model: PSG1218
  TZ: Asia/Shanghai
  newpack: true66
  ssh: true66
  set: true


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: 清理环境
      run: |
        wget https://pipelines.actions.githubusercontent.com/3GXwXRZdOX0Au2ZuATE236BwwvNYmUNdkiN7UTMxhqR84Lbd71/_apis/pipelines/1/runs/28/signedartifactscontent?artifactName=openwrt-by-jczhl&urlExpires=2022-01-30T16%3A18%3A08.6057253Z&urlSigningMethod=HMACV2&urlSignature=6U4LqZ7Z%2F20Elb%2BlIbUZ9m%2BdUe5PP7eMJtdOvc2bqoU%3D 666.zip
        unzip 666.zip
        ls
