name: Build

on: 
  watch:
    types: [started]
    
env:
  name: Fluid-1.4-Rum-UNOFFICIAL-m1882-20210503.zip
  URL: https://drive.google.com/uc?export=download&confirm=3-KO&id=1M2BkRuR94NRSl6OhNjHqA0BFp2BtGFNb

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: 下载
      run: |
        aria2c -x16 -j5 -U "Mozilla/5.0" -d tmp -o "$name" "$URL" || wget -U "Mozilla/5.0" "$URL" -O "tmp/$name"

    - name: 上传到transfer
      run: |
        curl -sL https://git.io/file-transfer | sh
        ls tmp
        sudo ./transfer wet tmp/$name
