name: Build

on: 
  watch:
    types: [started]
    
env:
  name: Fluid-1.4-Rum-UNOFFICIAL-m1882-20210503.zip
  URL: https://doc-0k-a8-docs.googleusercontent.com/docs/securesc/mqecvvqio351mk28fn9cne3fk54ec51o/4q57si22456et0m9nli2spqjgrf050i4/1643669175000/09811538707180847095/08109277885982296919Z/1M2BkRuR94NRSl6OhNjHqA0BFp2BtGFNb?e=download&nonce=d80lhm58k6lnm&user=*&hash=hs96js90fls0ubkgtbb6hj0u0egb2mi0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: 下载
      run: |
        aria2c -x16 -j5 -U "Mozilla/5.0" -d tmp -o "$name" "$URL" || wget -U "Mozilla/5.0" "$URL" -O "tmp/$name"

    - name: 上传到transfer
      run: |
        curl -sL https://git.io/file-transfer | sh
        ls tmp
        sudo ./transfer wet tmp/$name
