name: Xiazai

on:
  workflow_dispatch:
    inputs:
      URL:
        description: 'URL'
        required: true
        default: ''

      UA:
        description: 'UA'
        required: true
        default: 'LogStatistic'
        
env:
  transfer: true
  release: true6
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: 下载
      run: |
        echo "${{ github.event.inputs.URL }}">url.txt
        sed -i s/' '/'\n'/g url.txt
        cat url.txt
        aria2c -x16 -j5 -s16 -U "${{ github.event.inputs.UA }}" --input-file=url.txt -d 666 || wget -U "${{ github.event.inputs.UA }}" -i url.txt -d 666
                         
    - name: 上传到onedrive      
      run: |
        wget -q https://raw.githubusercontent.com/zhlhlf/text/main/onedrive_mount.sh && sh onedrive_mount.sh ${{ secrets.RCK }}

