name: Xiazai

on:
  workflow_dispatch:
    inputs:
      URL:
        description: 'URL'
        required: true
        default: ''

      UA:
        description: 'UA'
        required: true
        default: 'LogStatistic'

      upload:
        description: 'fio one wss '
        required: true
        default: 'fio'
      
      split:
        description: 'split'
        required: true
        default: 'false'
        type: boolean
        
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: 下载
      run: |
        echo "${{ github.event.inputs.URL }}">url.txt
        sed -i s/' '/'\n'/g url.txt
        cat url.txt
        aria2c -x10 -U "${{ github.event.inputs.UA }}" --input-file=url.txt -d 666 || wget -U "${{ github.event.inputs.UA }}" -i url.txt -d 666
           
    - name: 检验和化分
      if: github.event.inputs.split == 'true'
      run: |
        m=$(ls 666)
        for i in $m; do
         if [[ $(du -sb 666/$i | awk '{print $1}') -gt 2097152000 ]];then
           echo -e "split packaging..." 
           split -d -b 2048m "666/$i" "666/$i"
           rm -rf "666/$i"
         fi    
        done

    - name: 上传文件
      run: |
        if [ ${{ github.event.inputs.upload }} = "one" ]; then
           wget -q https://raw.github.com/zhlhlf/text/main/onedrive_mount.sh && sh onedrive_mount.sh ${{ secrets.RCK }} 临时存放文件         
        else
           curl -sL https://git.io/file-transfer | sh 
           aa=${{ github.event.inputs.upload }}
           sh transfer.sh $aa
        fi
